<?php 
	$current_customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();
	$customIconEnable = Mage::helper('customericon/data')->customer_icon_enable();
	if($customIconEnable && $current_customer_id)
	{
		$customIcon = Mage::getModel('customericon/customericon')->load($current_customer_id, 'customer_id');
		$getImagePath = $customIcon->getImagePath();		
	 
		if($current_customer_id && $getImagePath)
		{		
			echo "<img src=\"". Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."vijaystore/customericon/images/".$getImagePath."\" alt='custom_icon_img' /> ";
		}
		else
		{
			echo "<img src=\"". Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."vijaystore/customericon/images/default/default_icon.png\" alt='custom_icon_img_default' /> ";
		}

	}
		
?>